### PR TITLE
Add Newsletter Signup to Resource Sidebar

### PR DESCRIPTION
**Pull request by bryantgillespie**

### CODE REVIEW

**Review by paescuj — COMMENTED** [review]
It has a little jump effect when focusing and unfocusing the field again without entering an email address (error due to missing email):
focus-jump


Also there's a jump effect during loading of the page because rendering of the input field is delayed, but not sure whether we can easily get rid of that:
loading-jump

Could we change the placeholder from "Your work email address..." to "Your email address..." to fit the field width?

**Comment by bryantgillespie** [comment]
> Also there's a jump effect during loading of the page because rendering of the input field is delayed, but not sure whether we can easily get rid of that:

Nature of the Hubspot Forms I think. Not sure how'd you fix that because there's no way to know how tall the form will be until the HS script processes it right?

> Could we change the placeholder from "Your work email address..." to "Your email address..." to fit the field width?

This is a HS thing. But I'll ask @MattatDirectus to update it.

**Comment by paescuj** [comment]
> Nature of the Hubspot Forms I think. Not sure how'd you fix that because there's no way to know how tall the form will be until the HS script processes it right?

Yeah, I'm afraid so.

> This is a HS thing. But I'll ask @MattatDirectus to update it.

Great, thanks 🙏

**Review by paescuj — APPROVED** [review]

**Comment by bryantgillespie** [comment]
@paescuj This latest commit unhides the error messages but there's obviously still a jump if there's a validation error.

I can work on a smooth animation that would help the UX on all the forms in a separate future PR because having this CTA live is a priority on the marketing side.

**Pull request merged**
